global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'springboot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'localhost:8083'  # Service A
          - 'localhost:8084'  # Service B
